<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datos [
    <!ENTITY  contacto "direccion, telefono">
    <!ELEMENT datos (alumno+,centro)>
    <!ELEMENT alumno (nombre)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT centro (denominacion)>
    <!ELEMENT denominacion (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    
]>

<datos>
    <alumno>
        <nombre>Juan Perez</nombre>
    </alumno>
    <alumno>
        <nombre>%contato;</nombre>
    </alumno>
    <centro>
        <denominacion>%contato;</denominacion>
        
    </centro>
</datos>