<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Alumnos [
    <!ELEMENT Alumnos (Alumno)+>
    <!ELEMENT Alumno (DNI, Nombre)>
    <!ELEMENT DNI (#PCDATA)>
    <!ELEMENT Nombre (#PCDATA)>
]>

<Alumnos>
    <!-- Documento1-->
    <Alumno>
    <DNI></DNI>
        <Nombre>Juan Ruiz</Nombre>
    </Alumno>
     <!-- Documento 2: -->
     <Alumno>
            <DNI>44304238J</DNI>
            <Nombre>Pedro Vargas</Nombre>
    </Alumno>
    <!-- Documento 3:-->  
    <Alumno>
            <Nombre>Eva Murillo</Nombre>
            <Nombre>Juan Ruiz </Nombre>
    </Alumno>
    <!-- Documento 4: -->
    <Alumno>
        <DNI>44304238J</DNI>
        <Nombre> </Nombre>
    </Alumno>
</Alumnos>


<!-- Slolucion: todos los texto son validos salvo el Documento 3  . Por que 
no se puede repetir un mismo elemento por en el dtd no te permite tener mas elemento del mismo
-->