<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Alumnos[
<!ELEMENT Alumnos (Alumno)+>
<!ELEMENT Alumno (DNI?,Nombre+)> 
<!ELEMENT DNI (#PCDATA)> 
<!ELEMENT Nombre (#PCDATA)>
]>

<!-- Documento1-->
<Alumnos>
    <Alumno>
        <Nombre>Juan Ruiz</Nombre>
    </Alumno>

    <Alumno>
        <DNI>55324412G</DNI>
        <Nombre>Pedro Vargas</Nombre>
    </Alumno>

    <!-- Documento 3: -->
    <Alumno>
        <DNI>78645534H</DNI>
        <DNI>44312211F</DNI>
    </Alumno>

    <!--   Documento 4:-->

    <Alumno>
        <DNI>55313424Y </DNI>
    </Alumno>

</Alumnos>


<!-- Solucion: Los unicos que son validos son el 1 y 2 por que tiene que aparecer  Nombre y  Dni puede  no aparecer   -->